import { Geist, Geist_Mono } from 'next/font/google'
import '../globals.css'
import { NextIntlClientProvider, useMessages } from 'next-intl'
import { getMessages } from '@/i18n/request'
import { I18nProvider } from '@/context/I18nContext'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function LocaleLayout({ children, params }) {
    const resolvedParams = await params
    const { locale } = resolvedParams
    const messages = await getMessages(locale)
    return (
        <html lang={locale}>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <NextIntlClientProvider messages={messages} locale={locale}>
                    <I18nProvider locale={locale} messages={messages}>
                        {children}
                    </I18nProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    )
}
